[build]
  publish = "."
  command = "echo No build command needed for static site"

[build.environment]
  NODE_VERSION = "18"

# Custom domain configuration
[context.production]
  command = "echo Production build"

[[redirects]]
  from = "/api/*"
  to = "https://studentevents-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/worker/*"
  to = "/worker/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python -m http.server 8000"
  targetPort = 8000
  port = 8888
  publish = "."
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
