[build]
builder = "NIXPACKS"
buildCommand = "cd backend-new && npm ci --omit=dev"

[deploy]
startCommand = "cd backend-new && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

