services:
  - type: web
    name: studentevents-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend-new && npm install
    startCommand: cd backend-new && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: StudentEvents
      - key: FRONTEND_URL
        value: https://afterstateevents.vercel.app
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

