services:
  - type: web
    name: studentevents-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      # Add your other environment variables in Render dashboard
    autoDeploy: true
